### ISSUE TITLE
uglify_reformat options - not quite so much beautification

### ISSUE THREAD

**Issue by bryanhanson** [jeroen/js#1]
First, thanks for these great tools you are writing Jeroen, I'm finding them very useful.  I know this is really a question downstream from your package, but I figured you would know the answer.  If I use `uglify_reformat(some_code, beautify = TRUE)`, code like this:

``` javascript
            svg.append("path")
           .attr("class", "line")
           .attr("class", "cursorGuide")
           .attr("d", line(hEnds));
```

Changes to this:

``` javascript
         svg.append("path").attr("class", "line").attr("class", "cursorGuide").attr("d", line(hEnds));
```

Do you know a way of preventing this particular beautification?  It sure makes things hard to read.  Thanks, Bryan

**Comment by jeroen** [comment]
I'm not sure if there is a way to control this. This question would be better suited for https://github.com/mishoo/UglifyJS2; I'm just writing the bindings.

**Comment by bryanhanson** [comment]
Will do, thanks again for your work with JavaScript tools.  I'll ask over at the Uglify site.
